# Generated by Django 5.1.3 on 2025-01-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_category_blog_updated_at_alter_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
